###
POST http://localhost:3005/register
Content-Type: application/json

{
    "username": "user7",
    "password": "1234",
    "email": "user7@gmail.com"
}


###
POST http://localhost:3005/login 
Content-Type: application/json 

{
  "username": "Gnani",
  "password": "1234"
}

###
GET http://localhost:3005/breweries/1/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkduYW5pIiwiaWF0IjoxNzE5NjAwMDEyfQ.Dz6vicjeJ6bjsUrFcVcxoSEdiytDouOs9PEvXlEhr7g
Content-Type: application/json

###
GET http://localhost:3005/reviews

###
POST http://localhost:3005/breweries/1/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkduYW5pIiwiaWF0IjoxNzE5NjAwMDEyfQ.Dz6vicjeJ6bjsUrFcVcxoSEdiytDouOs9PEvXlEhr7g
Content-Type: application/json 

{
  "breweryId": "4",
  "userId": "1",
  "comment": " Best vibes",
  "rating": "3"
}
