###
GET http://localhost:3004/reviews 


POST http://localhost:3004/register
Content-Type: application/json

{
    "username": "user2",
    "password": "1234",
    "email": "user2@gmail.com"
}

###
POST http://localhost:3004/login 
Content-Type: application/json 

{
  "username": "Gnani",
  "password": "1234"
}

###
POST http://localhost:3004/breweries/1/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkduYW5pIiwiaWF0IjoxNzE5NjAwMDEyfQ.Dz6vicjeJ6bjsUrFcVcxoSEdiytDouOs9PEvXlEhr7g
Content-Type: application/json

{
    "userId": "1",
    "review": "Good",
    "rating" : "4"
}

###
GET http://localhost:3004/breweries/1/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkduYW5pIiwiaWF0IjoxNzE5NjAwMDEyfQ.Dz6vicjeJ6bjsUrFcVcxoSEdiytDouOs9PEvXlEhr7g
Content-Type: application/json